In [7]:
import numpy as np
import pandas as pd
from IPython.display import display

pd.set_option('display.max_columns', 140)
pd.set_option('display.width', 180)

### 1. Đọc dữ liệu và kiểm tra tổng quan

In [8]:
DATA_PATH = "../../data/dataset1/dataset1_full.csv"

df_raw = pd.read_csv(DATA_PATH)
print('Dataset 1 full shape:', df_raw.shape)
print('Columns:', len(df_raw.columns))
display(pd.DataFrame({'column': df_raw.columns, 'dtype': [df_raw[c].dtype for c in df_raw.columns]}))
display(df_raw.head())

Dataset 1 full shape: (946, 54)
Columns: 54

                        column    dtype
0               transaction_id    int64
1                    timestamp   object
2                       city_x   object
3                      country   object
4                   store_type   object
5             product_category   object
6                 product_name   object
7                   unit_price  float64
8                     quantity    int64
9             discount_applied     bool
10              payment_method   object
11                 customer_id   object
12          customer_age_group   object
13             customer_gender   object
14              loyalty_member     bool
15  original_weather_condition   object
16      original_temperature_c  float64
17       original_holiday_name   object
18                total_amount  float64
19          timestamp_datetime   object
20                        date   object
21                        hour    int64
22                    location   object
23                      city_y   object
24                     borough   object
25               temperature_c  float64
26      apparent_temperature_c  float64
27           relative_humidity    int64
28            precipitation_mm  float64
29                     rain_mm  float64
30                weather_code    int64
31    weather_code_description   object
32           weather_condition   object
33          wind_speed_10m_kmh  float64
34             cloud_cover_pct    int64
35                    is_rainy     bool
36                    is_snowy     bool
37            is_precipitation     bool
38            weather_latitude  float64
39           weather_longitude  float64
40              weather_source   object
41       weather_spatial_level   object
42                holiday_name   object
43                holiday_type   object
44         is_official_holiday     bool
45         is_commercial_event     bool
46                       notes   object
47                  is_holiday     bool
48              is_pre_holiday     bool
49             is_post_holiday     bool
50     days_to_nearest_holiday    int64
51        nearest_holiday_name   object
52              holiday_source   object
53      holiday_calendar_scope   object

,transaction_id,timestamp,city_x,country,store_type,product_category,product_name,unit_price,quantity,discount_applied,payment_method,customer_id,customer_age_group,customer_gender,loyalty_member,original_weather_condition,original_temperature_c,original_holiday_name,total_amount,timestamp_datetime,date,hour,location,city_y,borough,temperature_c,apparent_temperature_c,relative_humidity,precipitation_mm,rain_mm,weather_code,weather_code_description,weather_condition,wind_speed_10m_kmh,cloud_cover_pct,is_rainy,is_snowy,is_precipitation,weather_latitude,weather_longitude,weather_source,weather_spatial_level,holiday_name,holiday_type,is_official_holiday,is_commercial_event,notes,is_holiday,is_pre_holiday,is_post_holiday,days_to_nearest_holiday,nearest_holiday_name,holiday_source,holiday_calendar_scope
0,10012,2023-01-01 06:16:26,New York,USA,Standalone,Coffee,Small Mocha,4.05,1,True,Credit Card,g4gks6r6,18-24,Male,False,Sunny,-1.1,New Year's Day,3.64,2023-01-01 06:16:26,2023-01-01,6,New York,New York,city_level,8.6,5.7,94,0.0,0.0,2,Partly cloudy,Cloudy,15.9,71,False,False,False,40.7128,-74.006,Open-Meteo Historical Weather API,city,New Year's Day,official,True,False,Actual New Year's Day,True,True,False,0,New Year's Day,data/holiday/nyc_2023_holiday_calendar.csv,NYC/US 2023 official holidays and selected com...
1,10015,2023-01-01 06:47:03,New York,USA,Standalone,Smoothie,Medium Berry Blast,5.50,1,False,Cash,xlpu0dk0,25-34,Male,False,Sunny,-1.1,New Year's Day,5.50,2023-01-01 06:47:03,2023-01-01,6,New York,New York,city_level,8.6,5.7,94,0.0,0.0,2,Partly cloudy,Cloudy,15.9,71,False,False,False,40.7128,-74.006,Open-Meteo Historical Weather API,city,New Year's Day,official,True,False,Actual New Year's Day,True,True,False,0,New Year's Day,data/holiday/nyc_2023_holiday_calendar.csv,NYC/US 2023 official holidays and selected com...
2,10020,2023-01-01 07:08:02,New York,USA,Standalone,Tea,Small Earl Grey,2.50,1,False,Cash,0cv3tlcx,25-34,NaN,False,Sunny,-1.1,New Year's Day,2.50,2023-01-01 07:08:02,2023-01-01,7,New York,New York,city_level,7.9,5.2,94,0.0,0.0,2,Partly cloudy,Cloudy,13.2,58,False,False,False,40.7128,-74.006,Open-Meteo Historical Weather API,city,New Year's Day,official,True,False,Actual New Year's Day,True,True,False,0,New Year's Day,data/holiday/nyc_2023_holiday_calendar.csv,NYC/US 2023 official holidays and selected com...
3,10037,2023-01-01 08:50:29,New York,USA,Standalone,Sandwich,Ham & Cheese Croissant,5.50,2,False,Credit Card,nkbtfshb,45-54,Male,False,Sunny,-1.1,New Year's Day,11.00,2023-01-01 08:50:29,2023-01-01,8,New York,New York,city_level,6.8,4.3,97,0.0,0.0,2,Partly cloudy,Cloudy,10.5,76,False,False,False,40.7128,-74.006,Open-Meteo Historical Weather API,city,New Year's Day,official,True,False,Actual New Year's Day,True,True,False,0,New Year's Day,data/holiday/nyc_2023_holiday_calendar.csv,NYC/US 2023 official holidays and selected com...
4,10040,2023-01-01 09:23:59,New York,USA,Standalone,Coffee,Large Latte,4.60,1,False,Credit Card,yjoaoejv,65+,Male,True,Sunny,-1.1,New Year's Day,4.60,2023-01-01 09:23:59,2023-01-01,9,New York,New York,city_level,8.0,5.5,94,0.0,0.0,2,Partly cloudy,Cloudy,11.9,67,False,False,False,40.7128,-74.006,Open-Meteo Historical Weather API,city,New Year's Day,official,True,False,Actual New Year's Day,True,True,False,0,New Year's Day,data/holiday/nyc_2023_holiday_calendar.csv,NYC/US 2023 official holidays and selected com...

In [14]:
df_raw["product_category"].nunique()

6

In [15]:
df_raw["product_category"].value_counts()

product_category
Coffee         453
Tea            236
Pastry         110
Sandwich        86
Smoothie        42
Merchandise     19
Name: count, dtype: int64

In [9]:
missing_summary = pd.DataFrame({
    'missing_count': df_raw.isna().sum(),
    'missing_pct': df_raw.isna().mean() * 100,
}).sort_values('missing_count', ascending=False)

print('Duplicate rows:', df_raw.duplicated().sum())
print('Duplicate transaction_id:', df_raw['transaction_id'].duplicated().sum() if 'transaction_id' in df_raw.columns else 'N/A')
display(missing_summary.head(25))

Duplicate rows: 0
Duplicate transaction_id: 0

                            missing_count  missing_pct
original_holiday_name                 927    97.991543
notes                                 878    92.811839
customer_age_group                     56     5.919662
customer_gender                        54     5.708245
original_weather_condition             30     3.171247
original_temperature_c                 30     3.171247
is_snowy                                0     0.000000
is_precipitation                        0     0.000000
is_rainy                                0     0.000000
weather_latitude                        0     0.000000
weather_longitude                       0     0.000000
weather_source                          0     0.000000
cloud_cover_pct                         0     0.000000
wind_speed_10m_kmh                      0     0.000000
weather_spatial_level                   0     0.000000
weather_condition                       0     0.000000
transaction_id                          0     0.000000
holiday_name                            0     0.000000
weather_code                            0     0.000000
holiday_type                            0     0.000000
is_official_holiday                     0     0.000000
is_commercial_event                     0     0.000000
is_holiday                              0     0.000000
is_pre_holiday                          0     0.000000
is_post_holiday                         0     0.000000

So sánh holiday/weather gốc với dữ liệu cào về

In [21]:
# So sánh holiday/weather gốc của Dataset 1 với dữ liệu enrich từ calendar + Open-Meteo

compare_df = df_raw.copy()

compare_df["date"] = pd.to_datetime(compare_df["date"], errors="coerce").dt.normalize()

# Chuẩn hóa holiday gốc
compare_df["original_holiday_name_clean"] = (
    compare_df["original_holiday_name"]
    .fillna("No Holiday")
    .astype(str)
    .str.strip()
)

compare_df["calendar_holiday_name_clean"] = (
    compare_df["holiday_name"]
    .fillna("No Holiday")
    .astype(str)
    .str.strip()
)

compare_df["original_is_holiday"] = compare_df["original_holiday_name_clean"].ne("No Holiday")
compare_df["calendar_is_holiday"] = compare_df["calendar_holiday_name_clean"].ne("No Holiday")

# Chuẩn hóa weather gốc
compare_df["original_temperature_c"] = pd.to_numeric(
    compare_df["original_temperature_c"],
    errors="coerce"
)

compare_df["temperature_c"] = pd.to_numeric(
    compare_df["temperature_c"],
    errors="coerce"
)

compare_df["temperature_diff"] = (
    compare_df["temperature_c"] - compare_df["original_temperature_c"]
)

compare_df["abs_temperature_diff"] = compare_df["temperature_diff"].abs()

compare_df["original_weather_condition_clean"] = (
    compare_df["original_weather_condition"]
    .fillna("Missing")
    .astype(str)
    .str.strip()
)

compare_df["open_meteo_weather_condition_clean"] = (
    compare_df["weather_condition"]
    .fillna("Missing")
    .astype(str)
    .str.strip()
)

compare_df["weather_condition_match"] = (
    compare_df["original_weather_condition_clean"]
    == compare_df["open_meteo_weather_condition_clean"]
)

compare_df["holiday_match"] = (
    compare_df["original_holiday_name_clean"]
    == compare_df["calendar_holiday_name_clean"]
)

print("===== Holiday comparison =====")
print("Rows:", len(compare_df))
print("Original holiday rows:", compare_df["original_is_holiday"].sum())
print("Calendar holiday rows:", compare_df["calendar_is_holiday"].sum())
print("Exact holiday name match:", compare_df["holiday_match"].mean() * 100)

display(
    pd.crosstab(
        compare_df["original_is_holiday"],
        compare_df["calendar_is_holiday"],
        rownames=["Original is holiday"],
        colnames=["Calendar is holiday"],
        margins=True
    )
)

print("\nHoliday mismatches:")
holiday_mismatch = compare_df[
    ~compare_df["holiday_match"]
][
    [
        "date",
        "timestamp",
        "original_holiday_name_clean",
        "calendar_holiday_name_clean",
        "is_holiday",
        "holiday_type",
        "is_official_holiday",
        "is_commercial_event",
    ]
].drop_duplicates()

display(holiday_mismatch.head(50))
print("Number of unique holiday mismatch dates:", holiday_mismatch["date"].nunique())


print("\n===== Temperature comparison =====")
display(
    compare_df[
        [
            "original_temperature_c",
            "temperature_c",
            "temperature_diff",
            "abs_temperature_diff",
        ]
    ].describe()
)

print("Missing original_temperature_c:", compare_df["original_temperature_c"].isna().sum())
print("Missing Open-Meteo temperature_c:", compare_df["temperature_c"].isna().sum())

print("\nRows with abs temperature difference >= 5C:")
display(
    compare_df[
        compare_df["abs_temperature_diff"] >= 5
    ][
        [
            "timestamp",
            "date",
            "hour",
            "original_temperature_c",
            "temperature_c",
            "temperature_diff",
            "original_weather_condition_clean",
            "open_meteo_weather_condition_clean",
        ]
    ].head(50)
)


print("\n===== Weather condition comparison =====")
print("Weather condition exact match:", compare_df["weather_condition_match"].mean() * 100)

display(
    pd.crosstab(
        compare_df["original_weather_condition_clean"],
        compare_df["open_meteo_weather_condition_clean"],
        rownames=["Original weather"],
        colnames=["Open-Meteo weather"],
        margins=True
    )
)

print("\nWeather condition mismatches:")
display(
    compare_df[
        ~compare_df["weather_condition_match"]
    ][
        [
            "timestamp",
            "date",
            "hour",
            "original_weather_condition_clean",
            "open_meteo_weather_condition_clean",
            "original_temperature_c",
            "temperature_c",
            "abs_temperature_diff",
        ]
    ].head(50)
)

===== Holiday comparison =====
Rows: 946
Original holiday rows: 19
Calendar holiday rows: 68
Exact holiday name match: 94.82029598308668

Calendar is holiday  False  True  All
Original is holiday
False                  878    49  927
True                     0    19   19
All                    878    68  946

Holiday mismatches:

          date            timestamp original_holiday_name_clean             calendar_holiday_name_clean  is_holiday         holiday_type  is_official_holiday  is_commercial_event
7   2023-01-02  2023-01-02 08:03:42                  No Holiday                 New Year's Day Observed        True    official_observed                 True                False
8   2023-01-02  2023-01-02 09:21:24                  No Holiday                 New Year's Day Observed        True    official_observed                 True                False
9   2023-01-02  2023-01-02 19:06:08                  No Holiday                 New Year's Day Observed        True    official_observed                 True                False
10  2023-01-02  2023-01-02 21:09:15                  No Holiday                 New Year's Day Observed        True    official_observed                 True                False
47  2023-01-16  2023-01-16 03:42:20                  No Holiday              Martin Luther King Jr. Day        True             official                 True                False
48  2023-01-16  2023-01-16 06:15:50                  No Holiday              Martin Luther King Jr. Day        True             official                 True                False
49  2023-01-16  2023-01-16 08:34:48                  No Holiday              Martin Luther King Jr. Day        True             official                 True                False
122 2023-02-14  2023-02-14 06:54:42                  No Holiday                         Valentine's Day        True           commercial                False                 True
123 2023-02-14  2023-02-14 08:27:52                  No Holiday                         Valentine's Day        True           commercial                False                 True
124 2023-02-14  2023-02-14 08:51:14                  No Holiday                         Valentine's Day        True           commercial                False                 True
125 2023-02-14  2023-02-14 13:10:25                  No Holiday                         Valentine's Day        True           commercial                False                 True
126 2023-02-14  2023-02-14 14:53:19                  No Holiday                         Valentine's Day        True           commercial                False                 True
193 2023-03-17  2023-03-17 07:03:39                  No Holiday                       St. Patrick's Day        True  cultural_commercial                False                 True
194 2023-03-17  2023-03-17 14:53:14                  No Holiday                       St. Patrick's Day        True  cultural_commercial                False                 True
250 2023-04-07  2023-04-07 19:18:36                  No Holiday                             Good Friday        True             cultural                False                False
256 2023-04-09  2023-04-09 06:08:20                  No Holiday                           Easter Sunday        True  cultural_commercial                False                 True
257 2023-04-09  2023-04-09 10:33:57                  No Holiday                           Easter Sunday        True  cultural_commercial                False                 True
258 2023-04-09  2023-04-09 12:45:59                  No Holiday                           Easter Sunday        True  cultural_commercial                False                 True
337 2023-05-14  2023-05-14 04:27:28                  No Holiday                            Mother's Day        True           commercial                False                 True
338 2023-05-14  2023-05-14 09:01:12                  No Holiday                            Mother's Day        True           commercial                False                 True
339 2023-05-14  2023-05-14 15:44:38                  No Holiday                            Mother's Day        True           commercial                False                 True
340 2023-05-14  2023-05-14 21:20:20                  No Holiday                            Mother's Day        True           commercial                False                 True
374 2023-05-29  2023-05-29 06:03:11                  No Holiday                            Memorial Day        True             official                 True                False
375 2023-05-29  2023-05-29 07:11:50                  No Holiday                            Memorial Day        True             official                 True                False
376 2023-05-29  2023-05-29 14:43:13                  No Holiday                            Memorial Day        True             official                 True                False
377 2023-05-29  2023-05-29 21:45:52                  No Holiday                            Memorial Day        True             official                 True                False
435 2023-06-18  2023-06-18 08:25:37                  No Holiday                            Father's Day        True           commercial                False                 True
627 2023-09-04  2023-09-04 14:09:27                  No Holiday                               Labor Day        True             official                 True                False
712 2023-10-09  2023-10-09 11:42:33                  No Holiday  Columbus Day / Indigenous Peoples' Day        True             official                 True                False
774 2023-10-31  2023-10-31 07:17:38                  No Holiday                               Halloween        True           commercial                False                 True
792 2023-11-10  2023-11-10 06:19:15                  No Holiday                   Veterans Day Observed        True    official_observed                 True                False
793 2023-11-10  2023-11-10 09:18:41                  No Holiday                   Veterans Day Observed        True    official_observed                 True                False
794 2023-11-10  2023-11-10 09:58:31                  No Holiday                   Veterans Day Observed        True    official_observed                 True                False
795 2023-11-10  2023-11-10 12:06:58                  No Holiday                   Veterans Day Observed        True    official_observed                 True                False
796 2023-11-10  2023-11-10 19:18:36                  No Holiday                   Veterans Day Observed        True    official_observed                 True                False
833 2023-11-23  2023-11-23 02:50:56                  No Holiday                        Thanksgiving Day        True             official                 True                False
834 2023-11-23  2023-11-23 07:36:31                  No Holiday                        Thanksgiving Day        True             official                 True                False
835 2023-11-23  2023-11-23 07:49:47                  No Holiday                        Thanksgiving Day        True             official                 True                False
836 2023-11-23  2023-11-23 08:05:01                  No Holiday                        Thanksgiving Day        True             official                 True                False
837 2023-11-23  2023-11-23 08:45:08                  No Holiday                        Thanksgiving Day        True             official                 True                False
838 2023-11-23  2023-11-23 09:18:17                  No Holiday                        Thanksgiving Day        True             official                 True                False
839 2023-11-23  2023-11-23 16:25:22                  No Holiday                        Thanksgiving Day        True             official                 True                False
840 2023-11-24  2023-11-24 09:22:05                  No Holiday                            Black Friday        True           commercial                False                 True
841 2023-11-24  2023-11-24 17:46:36                  No Holiday                            Black Friday        True           commercial                False                 True
842 2023-11-24  2023-11-24 18:10:19                  No Holiday                            Black Friday        True           commercial                False                 True
924 2023-12-24  2023-12-24 09:12:05                  No Holiday                           Christmas Eve        True           commercial                False                 True
925 2023-12-24  2023-12-24 09:31:14                  No Holiday                           Christmas Eve        True           commercial                False                 True
944 2023-12-31  2023-12-31 11:26:49                  No Holiday                          New Year's Eve        True           commercial                False                 True
945 2023-12-31  2023-12-31 14:14:15                  No Holiday                          New Year's Eve        True           commercial                False                 True

Number of unique holiday mismatch dates: 17

===== Temperature comparison =====

       original_temperature_c  temperature_c  temperature_diff  abs_temperature_diff
count              916.000000     946.000000        916.000000            916.000000
mean                13.357314      13.364376          0.015284              4.699345
std                  9.531260       9.187292          5.919718              3.596571
min                 -6.800000     -16.400000        -22.200000              0.000000
25%                  4.975000       5.900000         -3.900000              1.975000
50%                 13.300000      12.600000         -0.200000              3.900000
75%                 22.100000      21.000000          3.925000              6.800000
max                 31.600000      34.800000         18.400000             22.200000

Missing original_temperature_c: 30
Missing Open-Meteo temperature_c: 0

Rows with abs temperature difference >= 5C:

               timestamp       date  hour  original_temperature_c  temperature_c  temperature_diff original_weather_condition_clean open_meteo_weather_condition_clean
0    2023-01-01 06:16:26 2023-01-01     6                    -1.1            8.6               9.7                            Sunny                             Cloudy
1    2023-01-01 06:47:03 2023-01-01     6                    -1.1            8.6               9.7                            Sunny                             Cloudy
2    2023-01-01 07:08:02 2023-01-01     7                    -1.1            7.9               9.0                            Sunny                             Cloudy
3    2023-01-01 08:50:29 2023-01-01     8                    -1.1            6.8               7.9                            Sunny                             Cloudy
4    2023-01-01 09:23:59 2023-01-01     9                    -1.1            8.0               9.1                            Sunny                             Cloudy
5    2023-01-01 11:57:27 2023-01-01    11                    -1.1           10.6              11.7                            Sunny                             Cloudy
6    2023-01-01 14:11:17 2023-01-01    14                    -1.1           11.9              13.0                            Sunny                              Clear
9    2023-01-02 19:06:08 2023-01-02    19                     2.2            8.5               6.3                            Sunny                             Cloudy
10   2023-01-02 21:09:15 2023-01-02    21                     2.2            8.9               6.7                            Sunny                             Cloudy
11   2023-01-03 09:03:55 2023-01-03     9                     1.2            7.9               6.7                            Sunny                             Cloudy
12   2023-01-03 13:57:48 2023-01-03    13                     1.2            8.9               7.7                            Sunny                               Rain
13   2023-01-03 17:00:44 2023-01-03    17                     1.2           12.6              11.4                            Sunny                             Cloudy
14   2023-01-04 07:00:17 2023-01-04     7                     2.8           12.5               9.7                            Sunny                             Cloudy
15   2023-01-04 15:58:31 2023-01-04    15                     2.8           17.2              14.4                            Sunny                             Cloudy
16   2023-01-04 17:59:10 2023-01-04    17                     2.8           14.1              11.3                            Sunny                             Cloudy
17   2023-01-05 12:13:46 2023-01-05    12                     3.5           10.5               7.0                            Sunny                             Cloudy
18   2023-01-05 12:26:34 2023-01-05    12                     3.5           10.5               7.0                            Sunny                             Cloudy
19   2023-01-05 17:09:37 2023-01-05    17                     3.5            9.8               6.3                            Sunny                             Cloudy
20   2023-01-06 08:27:26 2023-01-06     8                    -1.6            5.2               6.8                            Sunny                               Rain
21   2023-01-06 08:44:33 2023-01-06     8                    -1.6            5.2               6.8                            Sunny                               Rain
22   2023-01-06 10:17:36 2023-01-06    10                    -1.6            6.2               7.8                            Sunny                               Rain
23   2023-01-06 11:49:55 2023-01-06    11                    -1.6            6.6               8.2                            Sunny                               Rain
24   2023-01-06 12:13:18 2023-01-06    12                    -1.6            6.9               8.5                            Sunny                               Rain
25   2023-01-06 20:02:18 2023-01-06    20                    -1.6            5.0               6.6                            Sunny                              Clear
28   2023-01-07 15:45:38 2023-01-07    15                     1.8            8.2               6.4                            Rainy                             Cloudy
40   2023-01-13 09:11:30 2023-01-13     9                    -3.3           11.2              14.5                           Cloudy                               Rain
45   2023-01-15 16:18:57 2023-01-15    16                    -1.9            5.2               7.1                           Cloudy                              Clear
52   2023-01-17 12:03:44 2023-01-17    12                    -1.0            4.7               5.7                           Cloudy                             Cloudy
54   2023-01-18 09:59:54 2023-01-18     9                     1.2            7.2               6.0                           Cloudy                               Rain
57   2023-01-21 07:19:18 2023-01-21     7                     5.4            0.1              -5.3                            Sunny                             Cloudy
58   2023-01-21 07:21:49 2023-01-21     7                     5.4            0.1              -5.3                            Sunny                             Cloudy
78   2023-01-26 12:12:26 2023-01-26    12                     1.8            7.7               5.9                            Sunny                             Cloudy
80   2023-01-27 07:22:10 2023-01-27     7                     3.7           -1.5              -5.2                           Cloudy                              Clear
85   2023-01-28 15:54:06 2023-01-28    15                     0.8           10.9              10.1                            Rainy                             Cloudy
86   2023-01-29 09:49:29 2023-01-29     9                    -6.8            2.8               9.6                            Sunny                             Cloudy
87   2023-01-29 16:35:00 2023-01-29    16                    -6.8           10.1              16.9                            Sunny                             Cloudy
88   2023-01-29 16:48:41 2023-01-29    16                    -6.8           10.1              16.9                            Sunny                             Cloudy
96   2023-02-04 01:59:20 2023-02-04     1                     5.8          -11.2             -17.0                            Rainy                             Cloudy
97   2023-02-04 07:31:53 2023-02-04     7                     5.8          -16.4             -22.2                            Rainy                              Clear
98   2023-02-04 15:50:28 2023-02-04    15                     5.8           -5.1             -10.9                            Rainy                             Cloudy
100  2023-02-05 12:51:23 2023-02-05    12                    -1.6            4.1               5.7                            Sunny                             Cloudy
103  2023-02-06 16:13:39 2023-02-06    16                     1.1            9.5               8.4                            Sunny                              Clear
107  2023-02-08 11:09:05 2023-02-08    11                     2.5            7.8               5.3                           Cloudy                             Cloudy
109  2023-02-09 13:10:48 2023-02-09    13                     1.4            7.8               6.4                            Rainy                             Cloudy
110  2023-02-09 16:21:40 2023-02-09    16                     1.4            9.6               8.2                            Rainy                             Cloudy
111  2023-02-09 16:25:10 2023-02-09    16                     1.4            9.6               8.2                            Rainy                             Cloudy
112  2023-02-10 11:12:34 2023-02-10    11                     1.5           13.4              11.9                           Cloudy                              Clear
113  2023-02-10 12:04:30 2023-02-10    12                     1.5           13.6              12.1                           Cloudy                              Clear
117  2023-02-12 10:16:57 2023-02-12    10                    -4.5            1.9               6.4                            Rainy                             Cloudy
118  2023-02-12 17:58:33 2023-02-12    17                    -4.5            6.1              10.6                            Rainy                             Cloudy

===== Weather condition comparison =====
Weather condition exact match: 9.30232558139535

Open-Meteo weather  Clear  Cloudy  Rain  Snow  All
Original weather
Cloudy                 75      88    21     0  184
Missing                 9      13     8     0   30
Rainy                  69     161    52     2  284
Snowy                   2       8     2     2   14
Sunny                 108     252    72     2  434
All                   263     522   155     6  946

Weather condition mismatches:

              timestamp       date  hour original_weather_condition_clean open_meteo_weather_condition_clean  original_temperature_c  temperature_c  abs_temperature_diff
0   2023-01-01 06:16:26 2023-01-01     6                            Sunny                             Cloudy                    -1.1            8.6                   9.7
1   2023-01-01 06:47:03 2023-01-01     6                            Sunny                             Cloudy                    -1.1            8.6                   9.7
2   2023-01-01 07:08:02 2023-01-01     7                            Sunny                             Cloudy                    -1.1            7.9                   9.0
3   2023-01-01 08:50:29 2023-01-01     8                            Sunny                             Cloudy                    -1.1            6.8                   7.9
4   2023-01-01 09:23:59 2023-01-01     9                            Sunny                             Cloudy                    -1.1            8.0                   9.1
5   2023-01-01 11:57:27 2023-01-01    11                            Sunny                             Cloudy                    -1.1           10.6                  11.7
6   2023-01-01 14:11:17 2023-01-01    14                            Sunny                              Clear                    -1.1           11.9                  13.0
7   2023-01-02 08:03:42 2023-01-02     8                            Sunny                             Cloudy                     2.2            5.1                   2.9
8   2023-01-02 09:21:24 2023-01-02     9                            Sunny                             Cloudy                     2.2            5.8                   3.6
9   2023-01-02 19:06:08 2023-01-02    19                            Sunny                             Cloudy                     2.2            8.5                   6.3
10  2023-01-02 21:09:15 2023-01-02    21                            Sunny                             Cloudy                     2.2            8.9                   6.7
11  2023-01-03 09:03:55 2023-01-03     9                            Sunny                             Cloudy                     1.2            7.9                   6.7
12  2023-01-03 13:57:48 2023-01-03    13                            Sunny                               Rain                     1.2            8.9                   7.7
13  2023-01-03 17:00:44 2023-01-03    17                            Sunny                             Cloudy                     1.2           12.6                  11.4
14  2023-01-04 07:00:17 2023-01-04     7                            Sunny                             Cloudy                     2.8           12.5                   9.7
15  2023-01-04 15:58:31 2023-01-04    15                            Sunny                             Cloudy                     2.8           17.2                  14.4
16  2023-01-04 17:59:10 2023-01-04    17                            Sunny                             Cloudy                     2.8           14.1                  11.3
17  2023-01-05 12:13:46 2023-01-05    12                            Sunny                             Cloudy                     3.5           10.5                   7.0
18  2023-01-05 12:26:34 2023-01-05    12                            Sunny                             Cloudy                     3.5           10.5                   7.0
19  2023-01-05 17:09:37 2023-01-05    17                            Sunny                             Cloudy                     3.5            9.8                   6.3
20  2023-01-06 08:27:26 2023-01-06     8                            Sunny                               Rain                    -1.6            5.2                   6.8
21  2023-01-06 08:44:33 2023-01-06     8                            Sunny                               Rain                    -1.6            5.2                   6.8
22  2023-01-06 10:17:36 2023-01-06    10                            Sunny                               Rain                    -1.6            6.2                   7.8
23  2023-01-06 11:49:55 2023-01-06    11                            Sunny                               Rain                    -1.6            6.6                   8.2
24  2023-01-06 12:13:18 2023-01-06    12                            Sunny                               Rain                    -1.6            6.9                   8.5
25  2023-01-06 20:02:18 2023-01-06    20                            Sunny                              Clear                    -1.6            5.0                   6.6
26  2023-01-07 09:45:00 2023-01-07     9                            Rainy                             Cloudy                     1.8            3.0                   1.2
27  2023-01-07 11:04:33 2023-01-07    11                            Rainy                             Cloudy                     1.8            4.4                   2.6
28  2023-01-07 15:45:38 2023-01-07    15                            Rainy                             Cloudy                     1.8            8.2                   6.4
29  2023-01-08 09:01:28 2023-01-08     9                            Sunny                              Clear                    -0.7           -0.6                   0.1
30  2023-01-08 13:53:06 2023-01-08    13                            Sunny                             Cloudy                    -0.7            3.5                   4.2
31  2023-01-08 16:08:29 2023-01-08    16                            Sunny                             Cloudy                    -0.7            4.0                   4.7
32  2023-01-08 23:17:40 2023-01-08    23                            Sunny                             Cloudy                    -0.7            1.5                   2.2
33  2023-01-09 03:04:32 2023-01-09     3                            Sunny                               Rain                     4.3            2.5                   1.8
34  2023-01-09 09:01:16 2023-01-09     9                            Sunny                             Cloudy                     4.3            1.8                   2.5
35  2023-01-09 21:35:00 2023-01-09    21                            Sunny                              Clear                     4.3            1.1                   3.2
36  2023-01-10 10:42:52 2023-01-10    10                            Sunny                             Cloudy                     1.7            2.7                   1.0
37  2023-01-10 12:00:13 2023-01-10    12                            Sunny                             Cloudy                     1.7            5.2                   3.5
38  2023-01-11 13:23:56 2023-01-11    13                            Sunny                             Cloudy                     0.6            3.5                   2.9
39  2023-01-12 10:31:23 2023-01-12    10                            Rainy                               Rain                     0.8            4.7                   3.9
40  2023-01-13 09:11:30 2023-01-13     9                           Cloudy                               Rain                    -3.3           11.2                  14.5
41  2023-01-14 18:44:19 2023-01-14    18                            Sunny                             Cloudy                    -1.4            0.8                   2.2
43  2023-01-15 10:47:07 2023-01-15    10                           Cloudy                              Clear                    -1.9           -0.4                   1.5
44  2023-01-15 11:53:04 2023-01-15    11                           Cloudy                              Clear                    -1.9            0.6                   2.5
45  2023-01-15 16:18:57 2023-01-15    16                           Cloudy                              Clear                    -1.9            5.2                   7.1
46  2023-01-15 20:11:46 2023-01-15    20                           Cloudy                              Clear                    -1.9            1.5                   3.4
47  2023-01-16 03:42:20 2023-01-16     3                            Sunny                             Cloudy                    -0.8           -2.2                   1.4
48  2023-01-16 06:15:50 2023-01-16     6                            Sunny                             Cloudy                    -0.8           -2.0                   1.2
49  2023-01-16 08:34:48 2023-01-16     8                          Missing                             Cloudy                     NaN           -0.7                   NaN
53  2023-01-18 07:41:21 2023-01-18     7                           Cloudy                              Clear                     1.2            4.9                   3.7

### 2. Helper functions

In [ ]:
# chuyển một cột dữ liệu về kiểu Boolean
def to_bool(series, default=False):
    mapping = {
        'true': True,
        'false': False,
        '1': True,
        '0': False,
        'yes': True,
        'no': False,
        'y': True,
        'n': False,
    }
    if series.dtype == bool:
        return series.fillna(default).astype(bool)
    return series.astype(str).str.strip().str.lower().map(mapping).fillna(default).astype(bool)

# lấy giá trị xuất hiện nhiều nhất trong một cột dữ liệu
def first_mode(series):
    non_missing = series.dropna()
    if non_missing.empty:
        return pd.NA
    mode_values = non_missing.mode()
    return mode_values.iloc[0] if not mode_values.empty else non_missing.iloc[0]

# tính ngưỡng phát hiện outlier bằng phương pháp IQR
def iqr_bounds(series, multiplier=1.5):
    q1 = series.quantile(0.25)
    q3 = series.quantile(0.75)
    iqr = q3 - q1
    return q1 - multiplier * iqr, q3 + multiplier * iqr

### 3. Chuẩn hóa schema transaction-level

Dataset 1 chỉ có địa điểm ở cấp city. Để dùng chung schema với Dataset 2, ta tạo:

```text
city = New York
area = city_level_unknown
location_level = city
```

In [18]:
df = df_raw.copy()

df['source_dataset'] = 'dataset1'
df['transaction_datetime'] = pd.to_datetime(
    df['timestamp_datetime'] if 'timestamp_datetime' in df.columns else df['timestamp'],
    errors='coerce',
)
df['date'] = df['transaction_datetime'].dt.normalize()
df['month'] = df['transaction_datetime'].dt.month
df['weekday'] = df['transaction_datetime'].dt.day_name()
df['weekday_num'] = df['transaction_datetime'].dt.dayofweek
df['hour'] = df['transaction_datetime'].dt.hour
df['is_weekend'] = df['weekday_num'].isin([5, 6])

city_candidates = [col for col in ['city_y', 'city_x', 'city'] if col in df.columns]
df['city'] = df[city_candidates[0]] if city_candidates else 'New York'
for col in city_candidates[1:]:
    df['city'] = df['city'].fillna(df[col])
df['city'] = df['city'].fillna('New York')
df['area'] = 'city_level_unknown'
df['location_level'] = 'city'
df['location'] = df['city']
df['store_id'] = pd.NA
df['store_location'] = df['city']

df['product_category'] = df['product_category'].astype(str).str.strip()
df['product_detail_clean'] = df['product_name'].astype(str).str.strip() if 'product_name' in df.columns else pd.NA

df['unit_price'] = pd.to_numeric(df['unit_price'], errors='coerce')
df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce')
df['revenue'] = pd.to_numeric(df['total_amount'], errors='coerce')
df['transaction_count'] = 1

numeric_external_cols = [
    'temperature_c',
    'apparent_temperature_c',
    'relative_humidity',
    'precipitation_mm',
    'rain_mm',
    'weather_code',
    'wind_speed_10m_kmh',
    'cloud_cover_pct',
    'days_to_nearest_holiday',
]
for col in numeric_external_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

bool_cols = [
    'is_rainy',
    'is_snowy',
    'is_precipitation',
    'is_holiday',
    'is_official_holiday',
    'is_commercial_event',
    'is_pre_holiday',
    'is_post_holiday',
    'discount_applied',
    'loyalty_member',
]
for col in bool_cols:
    if col in df.columns:
        df[col] = to_bool(df[col])

common_transaction_cols = [
    'source_dataset',
    'transaction_id',
    'transaction_datetime',
    'date',
    'month',
    'weekday',
    'weekday_num',
    'hour',
    'is_weekend',
    'city',
    'area',
    'location_level',
    'location',
    'store_id',
    'store_location',
    'product_category',
    'product_detail_clean',
    'unit_price',
    'quantity',
    'transaction_count',
    'revenue',
    'temperature_c',
    'apparent_temperature_c',
    'relative_humidity',
    'precipitation_mm',
    'rain_mm',
    'weather_condition',
    'weather_code',
    'wind_speed_10m_kmh',
    'cloud_cover_pct',
    'is_rainy',
    'is_snowy',
    'is_precipitation',
    'weather_spatial_level',
    'is_holiday',
    'holiday_name',
    'holiday_type',
    'is_official_holiday',
    'is_commercial_event',
    'is_pre_holiday',
    'is_post_holiday',
    'days_to_nearest_holiday',
    'nearest_holiday_name',
]

df1_clean = df[common_transaction_cols].copy()

print('Dataset 1 clean transaction-level shape:', df1_clean.shape)
display(df1_clean.head())

Dataset 1 clean transaction-level shape: (946, 43)

,source_dataset,transaction_id,transaction_datetime,date,month,weekday,weekday_num,hour,is_weekend,city,area,location_level,location,store_id,store_location,product_category,product_detail_clean,unit_price,quantity,transaction_count,revenue,temperature_c,apparent_temperature_c,relative_humidity,precipitation_mm,rain_mm,weather_condition,weather_code,wind_speed_10m_kmh,cloud_cover_pct,is_rainy,is_snowy,is_precipitation,weather_spatial_level,is_holiday,holiday_name,holiday_type,is_official_holiday,is_commercial_event,is_pre_holiday,is_post_holiday,days_to_nearest_holiday,nearest_holiday_name
0,dataset1,10012,2023-01-01 06:16:26,2023-01-01,1,Sunday,6,6,True,New York,city_level_unknown,city,New York,<NA>,New York,Coffee,Small Mocha,4.05,1,1,3.64,8.6,5.7,94,0.0,0.0,Cloudy,2,15.9,71,False,False,False,city,True,New Year's Day,official,True,False,True,False,0,New Year's Day
1,dataset1,10015,2023-01-01 06:47:03,2023-01-01,1,Sunday,6,6,True,New York,city_level_unknown,city,New York,<NA>,New York,Smoothie,Medium Berry Blast,5.50,1,1,5.50,8.6,5.7,94,0.0,0.0,Cloudy,2,15.9,71,False,False,False,city,True,New Year's Day,official,True,False,True,False,0,New Year's Day
2,dataset1,10020,2023-01-01 07:08:02,2023-01-01,1,Sunday,6,7,True,New York,city_level_unknown,city,New York,<NA>,New York,Tea,Small Earl Grey,2.50,1,1,2.50,7.9,5.2,94,0.0,0.0,Cloudy,2,13.2,58,False,False,False,city,True,New Year's Day,official,True,False,True,False,0,New Year's Day
3,dataset1,10037,2023-01-01 08:50:29,2023-01-01,1,Sunday,6,8,True,New York,city_level_unknown,city,New York,<NA>,New York,Sandwich,Ham & Cheese Croissant,5.50,2,1,11.00,6.8,4.3,97,0.0,0.0,Cloudy,2,10.5,76,False,False,False,city,True,New Year's Day,official,True,False,True,False,0,New Year's Day
4,dataset1,10040,2023-01-01 09:23:59,2023-01-01,1,Sunday,6,9,True,New York,city_level_unknown,city,New York,<NA>,New York,Coffee,Large Latte,4.60,1,1,4.60,8.0,5.5,94,0.0,0.0,Cloudy,2,11.9,67,False,False,False,city,True,New Year's Day,official,True,False,True,False,0,New Year's Day

### 4. Kiểm tra chất lượng sau chuẩn hóa

In [12]:
key_cols = ['transaction_datetime', 'date', 'hour', 'city', 'area', 'product_category', 'revenue']
quality_checks = {
    'rows': len(df1_clean),
    'duplicate_transaction_id': int(df1_clean['transaction_id'].duplicated().sum()),
    'invalid_transaction_datetime': int(df1_clean['transaction_datetime'].isna().sum()),
    'missing_key_values': int(df1_clean[key_cols].isna().sum().sum()),
    'non_positive_revenue': int((df1_clean['revenue'] <= 0).sum()),
    'non_positive_quantity': int((df1_clean['quantity'] <= 0).sum()),
    'non_positive_unit_price': int((df1_clean['unit_price'] <= 0).sum()),
    'missing_weather_condition': int(df1_clean['weather_condition'].isna().sum()),
    'missing_temperature_c': int(df1_clean['temperature_c'].isna().sum()),
    'missing_holiday_name': int(df1_clean['holiday_name'].isna().sum()),
}
display(pd.Series(quality_checks, name='value').to_frame())

display(
    pd.DataFrame({
        'missing_count': df1_clean.isna().sum(),
        'missing_pct': df1_clean.isna().mean() * 100,
    }).sort_values('missing_count', ascending=False).head(20)
)

                              value
rows                            946
duplicate_transaction_id          0
invalid_transaction_datetime      0
missing_key_values                0
non_positive_revenue              0
non_positive_quantity             0
non_positive_unit_price           0
missing_weather_condition         0
missing_temperature_c             0
missing_holiday_name              0

                        missing_count  missing_pct
store_id                          946        100.0
source_dataset                      0          0.0
apparent_temperature_c              0          0.0
precipitation_mm                    0          0.0
rain_mm                             0          0.0
weather_condition                   0          0.0
weather_code                        0          0.0
wind_speed_10m_kmh                  0          0.0
cloud_cover_pct                     0          0.0
is_rainy                            0          0.0
is_snowy                            0          0.0
is_precipitation                    0          0.0
weather_spatial_level               0          0.0
is_holiday                          0          0.0
holiday_name                        0          0.0
holiday_type                        0          0.0
is_official_holiday                 0          0.0
is_commercial_event                 0          0.0
is_pre_holiday                      0          0.0
is_post_holiday                     0          0.0

In [13]:
revenue_lower, revenue_upper = iqr_bounds(df1_clean['revenue'])
unit_price_lower, unit_price_upper = iqr_bounds(df1_clean['unit_price'])

outlier_summary = pd.DataFrame(
    [
        {
            'field': 'revenue',
            'lower_bound': revenue_lower,
            'upper_bound': revenue_upper,
            'outlier_count': int(((df1_clean['revenue'] < revenue_lower) | (df1_clean['revenue'] > revenue_upper)).sum()),
        },
        {
            'field': 'unit_price',
            'lower_bound': unit_price_lower,
            'upper_bound': unit_price_upper,
            'outlier_count': int(((df1_clean['unit_price'] < unit_price_lower) | (df1_clean['unit_price'] > unit_price_upper)).sum()),
        },
    ]
)

display(outlier_summary)
display(df1_clean[['revenue', 'quantity', 'unit_price', 'temperature_c', 'precipitation_mm']].describe())

        field  lower_bound  upper_bound  outlier_count
0     revenue     -3.49375     15.05625             67
1  unit_price      0.35000      7.15000             19

          revenue    quantity  unit_price  temperature_c  precipitation_mm
count  946.000000  946.000000  946.000000     946.000000        946.000000
mean     6.887643    1.691332    4.075634      13.364376          0.167336
std      6.087638    1.098276    1.832968       9.187292          0.703506
min      1.600000    1.000000    2.000000     -16.400000          0.000000
25%      3.462500    1.000000    2.900000       5.900000          0.000000
50%      5.000000    1.000000    3.800000      12.600000          0.000000
75%      8.100000    2.000000    4.600000      21.000000          0.000000
max     75.000000    9.000000   15.000000      34.800000          8.600000

### 5. Aggregate về cấp mô hình

Không nên train ở transaction-level nếu mục tiêu là dự đoán doanh thu theo external factors. Cấp hợp lý hơn:

```text
date + hour + city + area + product_category
```

Dataset 1 có `area = city_level_unknown`, vì dữ liệu chỉ ở cấp thành phố.

In [ ]:
# Tổng hợp doanh thu theo từng giờ, từng ngày, từng khu vực, từng loại sản phẩm

group_cols_total = [
    'source_dataset',
    'date',
    'month',
    'weekday',
    'weekday_num',
    'hour',
    'is_weekend',
    'city',
    'area',
    'location_level',
]

df1_hourly_total = (
    df1_clean.groupby(group_cols_total, dropna=False)
    .agg(
        revenue=('revenue', 'sum'),
        quantity=('quantity', 'sum'),
        transaction_count=('transaction_count', 'sum'),
        avg_transaction_value=('revenue', 'mean'),
        avg_unit_price=('unit_price', 'mean'),

        temperature_c=('temperature_c', 'mean'),
        apparent_temperature_c=('apparent_temperature_c', 'mean'),
        relative_humidity=('relative_humidity', 'mean'),
        precipitation_mm=('precipitation_mm', 'mean'),
        wind_speed_10m_kmh=('wind_speed_10m_kmh', 'mean'),
        cloud_cover_pct=('cloud_cover_pct', 'mean'),

        weather_condition=('weather_condition', first_mode),
        is_rainy=('is_rainy', first_mode),
        is_snowy=('is_snowy', first_mode),
        is_precipitation=('is_precipitation', first_mode),
        weather_spatial_level=('weather_spatial_level', first_mode),

        is_holiday=('is_holiday', first_mode),
        holiday_name=('holiday_name', first_mode),
        holiday_type=('holiday_type', first_mode),
        is_official_holiday=('is_official_holiday', first_mode),
        is_commercial_event=('is_commercial_event', first_mode),
        is_pre_holiday=('is_pre_holiday', first_mode),
        is_post_holiday=('is_post_holiday', first_mode),
        days_to_nearest_holiday=('days_to_nearest_holiday', 'min'),
        nearest_holiday_name=('nearest_holiday_name', first_mode),
    )
    .reset_index()
)

round_cols = [
    'revenue',
    'avg_transaction_value',
    'avg_unit_price',
    'temperature_c',
    'apparent_temperature_c',
    'precipitation_mm',
]

for col in round_cols:
    df1_hourly_total[col] = df1_hourly_total[col].round(3)

print('Dataset 1 hourly total aggregate shape:', df1_hourly_total.shape)
display(df1_hourly_total.head())
display(df1_hourly_total['revenue'].describe())

Dataset 1 hourly aggregate shape: (919, 36)

,source_dataset,date,month,weekday,weekday_num,hour,is_weekend,city,area,location_level,product_category,revenue,quantity,transaction_count,avg_transaction_value,avg_unit_price,temperature_c,apparent_temperature_c,relative_humidity,precipitation_mm,wind_speed_10m_kmh,cloud_cover_pct,weather_condition,is_rainy,is_snowy,is_precipitation,weather_spatial_level,is_holiday,holiday_name,holiday_type,is_official_holiday,is_commercial_event,is_pre_holiday,is_post_holiday,days_to_nearest_holiday,nearest_holiday_name
0,dataset1,2023-01-01,1,Sunday,6,6,True,New York,city_level_unknown,city,Coffee,3.64,1,1,3.64,4.05,8.6,5.7,94.0,0.0,15.9,71.0,Cloudy,False,False,False,city,True,New Year's Day,official,True,False,True,False,0,New Year's Day
1,dataset1,2023-01-01,1,Sunday,6,6,True,New York,city_level_unknown,city,Smoothie,5.50,1,1,5.50,5.50,8.6,5.7,94.0,0.0,15.9,71.0,Cloudy,False,False,False,city,True,New Year's Day,official,True,False,True,False,0,New Year's Day
2,dataset1,2023-01-01,1,Sunday,6,7,True,New York,city_level_unknown,city,Tea,2.50,1,1,2.50,2.50,7.9,5.2,94.0,0.0,13.2,58.0,Cloudy,False,False,False,city,True,New Year's Day,official,True,False,True,False,0,New Year's Day
3,dataset1,2023-01-01,1,Sunday,6,8,True,New York,city_level_unknown,city,Sandwich,11.00,2,1,11.00,5.50,6.8,4.3,97.0,0.0,10.5,76.0,Cloudy,False,False,False,city,True,New Year's Day,official,True,False,True,False,0,New Year's Day
4,dataset1,2023-01-01,1,Sunday,6,9,True,New York,city_level_unknown,city,Coffee,4.60,1,1,4.60,4.60,8.0,5.5,94.0,0.0,11.9,67.0,Cloudy,False,False,False,city,True,New Year's Day,official,True,False,True,False,0,New Year's Day

count    919.000000
mean       7.090000
std        6.274396
min        1.600000
25%        3.500000
50%        5.000000
75%        8.400000
max       75.000000
Name: revenue, dtype: float64

### 6. Feature list cho model và leakage control

In [23]:
target_col = 'revenue'

time_features = ['month', 'weekday_num', 'hour', 'is_weekend']
product_features = ['product_category']
weather_features = [
    'temperature_c',
    'apparent_temperature_c',
    'relative_humidity',
    'precipitation_mm',
    'wind_speed_10m_kmh',
    'cloud_cover_pct',
    'weather_condition',
    'is_rainy',
    'is_snowy',
    'is_precipitation',
]
holiday_features = [
    'is_holiday',
    'holiday_type',
    'is_official_holiday',
    'is_commercial_event',
    'is_pre_holiday',
    'is_post_holiday',
    'days_to_nearest_holiday',
]
location_features = ['area', 'location_level']

feature_set_no_location = time_features + product_features + weather_features + holiday_features
feature_set_with_location = feature_set_no_location + location_features

leakage_or_post_sale_cols = [
    'quantity',
    'transaction_count',
    'avg_transaction_value',
    'avg_unit_price',
]

print('Target:', target_col)
print('\nFeature set 1 - không dùng location:')
print(feature_set_no_location)
print('\nFeature set 2 - có dùng location:')
print(feature_set_with_location)
print('\nKhông dùng trong model chính vì leakage/post-sale:')
print(leakage_or_post_sale_cols)

Target: revenue

Feature set 1 - không dùng location:
['month', 'weekday_num', 'hour', 'is_weekend', 'product_category', 'temperature_c', 'apparent_temperature_c', 'relative_humidity', 'precipitation_mm', 'wind_speed_10m_kmh', 'cloud_cover_pct', 'weather_condition', 'is_rainy', 'is_snowy', 'is_precipitation', 'is_holiday', 'holiday_type', 'is_official_holiday', 'is_commercial_event', 'is_pre_holiday', 'is_post_holiday', 'days_to_nearest_holiday']

Feature set 2 - có dùng location:
['month', 'weekday_num', 'hour', 'is_weekend', 'product_category', 'temperature_c', 'apparent_temperature_c', 'relative_humidity', 'precipitation_mm', 'wind_speed_10m_kmh', 'cloud_cover_pct', 'weather_condition', 'is_rainy', 'is_snowy', 'is_precipitation', 'is_holiday', 'holiday_type', 'is_official_holiday', 'is_commercial_event', 'is_pre_holiday', 'is_post_holiday', 'days_to_nearest_holiday', 'area', 'location_level']

Không dùng trong model chính vì leakage/post-sale:
['quantity', 'transaction_count', 'avg_transaction_value', 'avg_unit_price']

### 7. Gợi ý xử lý mất cân bằng dữ liệu khi gộp với Dataset 2

In [ ]:
dataset1_balance_reference = pd.DataFrame(
    {
        'level': ['transaction_level', 'hourly_aggregate_level'],
        'dataset1_rows': [len(df1_clean), len(df1_hourly)],
        'note': [
            'Không nên train model external-only trực tiếp ở transaction-level.',
            'Nên dùng cấp này để gộp với Dataset 2 rồi đánh giá imbalance.',
        ],
    }
)

display(dataset1_balance_reference)

print('Hướng xử lý imbalance sau khi có Dataset 2 aggregate:')
print('1. Train chung bình thường nhưng report metric riêng theo source_dataset.')
print('2. Thử sample_weight để Dataset 1 không bị Dataset 2 lấn át.')
print('3. Thử downsample Dataset 2 như experiment phụ để kiểm tra sampling variation.')
print('4. Thử train trên common period 2023-01 đến 2023-06 để giảm lệch temporal scope.')
print('5. So sánh model có location và không location như plan đã chốt.')

                    level  dataset1_rows                                               note
0       transaction_level            946  Không nên train model external-only trực tiếp ...
1  hourly_aggregate_level            919  Nên dùng cấp này để gộp với Dataset 2 rồi đánh...

Hướng xử lý imbalance sau khi có Dataset 2 aggregate:
1. Train chung bình thường nhưng report metric riêng theo source_dataset.
2. Thử sample_weight để Dataset 1 không bị Dataset 2 lấn át.
3. Thử downsample Dataset 2 như experiment phụ để kiểm tra sampling variation.
4. Thử train trên common period 2023-01 đến 2023-06 để giảm lệch temporal scope.
5. So sánh model có location và không location như plan đã chốt.